services:
  db:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    volumes:
      - todo_pgdata:/var/lib/postgresql/data

volumes:
  todo_pgdata:
